//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja_na_projekt.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kwadrat", ReplyAction="*")]
        double kwadrat(double a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/kwadrat", ReplyAction="*")]
        System.Threading.Tasks.Task<double> kwadratAsync(double a);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/trojkat", ReplyAction="*")]
        double trojkat(double a, double h);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/trojkat", ReplyAction="*")]
        System.Threading.Tasks.Task<double> trojkatAsync(double a, double h);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/prostakat", ReplyAction="*")]
        double prostakat(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/prostakat", ReplyAction="*")]
        System.Threading.Tasks.Task<double> prostakatAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rownoleglobok", ReplyAction="*")]
        double rownoleglobok(double a, double h);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/rownoleglobok", ReplyAction="*")]
        System.Threading.Tasks.Task<double> rownoleglobokAsync(double a, double h);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/trapez", ReplyAction="*")]
        double trapez(double a, double b, double h);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/trapez", ReplyAction="*")]
        System.Threading.Tasks.Task<double> trapezAsync(double a, double b, double h);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Aplikacja_na_projekt.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Aplikacja_na_projekt.ServiceReference1.WebService1Soap>, Aplikacja_na_projekt.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double kwadrat(double a) {
            return base.Channel.kwadrat(a);
        }
        
        public System.Threading.Tasks.Task<double> kwadratAsync(double a) {
            return base.Channel.kwadratAsync(a);
        }
        
        public double trojkat(double a, double h) {
            return base.Channel.trojkat(a, h);
        }
        
        public System.Threading.Tasks.Task<double> trojkatAsync(double a, double h) {
            return base.Channel.trojkatAsync(a, h);
        }
        
        public double prostakat(double a, double b) {
            return base.Channel.prostakat(a, b);
        }
        
        public System.Threading.Tasks.Task<double> prostakatAsync(double a, double b) {
            return base.Channel.prostakatAsync(a, b);
        }
        
        public double rownoleglobok(double a, double h) {
            return base.Channel.rownoleglobok(a, h);
        }
        
        public System.Threading.Tasks.Task<double> rownoleglobokAsync(double a, double h) {
            return base.Channel.rownoleglobokAsync(a, h);
        }
        
        public double trapez(double a, double b, double h) {
            return base.Channel.trapez(a, b, h);
        }
        
        public System.Threading.Tasks.Task<double> trapezAsync(double a, double b, double h) {
            return base.Channel.trapezAsync(a, b, h);
        }
    }
}
